version: '3.8'

services:
  php:
    image: php:8.0-cli
    container_name: php_app
    volumes:
      - .:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
